const portfolioProjects = [
    {
        title: '2019 year',
        data: [
            {
                title: 'Warehouse Management System',
                description: 't is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. ',
                date: 'March - Present, 2019',
                img: '/img/projects/vanee-project.png',
                type: 'Work',
                appType: 'Web Application',
                appTypeColor: { backgroundColor: '#fed656' },
                url: '',
            },
            {
                title: 'BidKid ZOHO CRM integration',
                description: 't is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. ',
                date: 'February, 2019',
                img: '/img/projects/bidkid-project.png',
                type: 'Work',
                appType: 'Web Application',
                appTypeColor: { backgroundColor: '#fed656' },
                url: '',
            },
        ],
    },
    {
        title: '2018 year',
        data: [
            {
                title: 'Central Parks Check-in Game',
                description: 't is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. ',
                date: 'December, 2018',
                img: '/img/projects/central-parks-project.png',
                type: 'Work',
                appType: 'Web Application',
                appTypeColor: { backgroundColor: '#fed656' },
                url: '',
            },
            {
                title: 'Mobile App & Schedule System',
                description: 't is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. ',
                date: 'November, 2018',
                img: '/img/projects/wild-goose-chase-project.png',
                type: 'Work',
                appType: 'Web & Mobile Applications',
                appTypeColor: { backgroundColor: '#0659a5' },
                url: '',
            },
            {
                title: 'Waukegan Park District',
                description: 't is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. ',
                date: 'August, 2018',
                img: '/img/projects/park-district-project.png',
                type: 'Work',
                appType: 'Mobile Application',
                appTypeColor: { backgroundColor: '#0659a5' },
                url: '',
            },
            {
                title: 'Vertabiz Mobile App',
                description: 't is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. ',
                date: 'June, 2018',
                img: '/img/projects/vertabiz-project.png',
                type: 'Work',
                appType: 'Mobile Application',
                appTypeColor: { backgroundColor: '#0659a5' },
                url: '',
            },
            {
                title: 'ReactJs Games Forum',
                description: 't is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using \'Content here, content here\', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. ',
                date: 'February, 2018',
                img: '/img/projects/react-forum.jpg',
                type: 'Personal',
                appType: 'Web Application',
                appTypeColor: { backgroundColor: '#fed656' },
                url: '',
            },
        ],
    },
    {
        title: '2017 year',
        data: [
            {
                title: 'Dealer eProcess Websites Re-skin',
                description: 'Most of my daily jobs was re-skin web sites for dealers',
                date: 'January-December, 2017',
                img: '/img/projects/dealer-eprocess.png',
                type: 'Work',
                appType: 'Website',
                appTypeColor: { backgroundColor: '#429934' },
                url: '',
            },
            {
                title: 'Dealer eProces Images Swipe',
                description: '',
                date: 'October, 2017',
                img: '/img/projects/swipe.jpg',
                type: 'Work',
                appType: 'Script',
                appTypeColor: { backgroundColor: '#ae3738' },
                url: '',
            },
            {
                title: 'PHP Auto Parts Search',
                description: 'Most of my daily jobs was re-skin web sites for dealers',
                date: 'June, 2017',
                img: '/img/projects/php-parts-project.png',
                type: 'Personal',
                appType: 'Web Application',
                appTypeColor: { backgroundColor: '#fed656' },
                url: '',
            },
            {
                title: 'Heathy Living Skills',
                description: 'Most of my daily jobs was re-skin web sites for dealers',
                date: 'December, 2017',
                img: '/img/projects/healthy_living_skills.png',
                type: 'Client',
                appType: 'Website',
                appTypeColor: { backgroundColor: '#429934' },
                url: '',
            },
        ],
    },
    {
        title: '2016 year',
        data: [
            {
                title: 'Floral Glory',
                description: 'Landing site for Nicotac sugar-free nicotine chewing gum.',
                date: 'October, 2016',
                img: '/img/projects/floralglorydesign.png',
                type: 'Client',
                appType: 'Website',
                appTypeColor: { backgroundColor: '#429934' },
                url: '',
            },

            {
                title: 'JakECig',
                description: 'JAK ECIG is an Illinois based ECIG manufacturer that has captured an amazing offline customer base through retail distribution channels since 2012. This places JAK ECIG is the #1 independent private owned brand',
                date: 'August, 2016',
                img: '/img/projects/jakecig-project.png',
                type: 'Client',
                appType: 'Website',
                appTypeColor: { backgroundColor: '#429934' },
                url: '',
            },
            {
                title: 'NicotacUSA',
                description: 'Landing site for Nicotac sugar-free nicotine chewing gum.',
                date: 'May, 2015',
                img: '/img/projects/nicotac-project.png',
                type: 'Client',
                appType: 'Website',
                appTypeColor: { backgroundColor: '#429934' },
                url: '',
            },
            {
                title: 'AnitaPro Cleaning',
                description: 'Cleaning services website.',
                date: 'March, 2016',
                img: '/img/projects/anitaproclean.png',
                type: 'Client',
                appType: 'Website',
                appTypeColor: { backgroundColor: '#429934' },
                url: '',
            },
            {
                title: 'Aaron Menu Pro',
                description: 'This is one of the first my JavaScript Project where I tried to understand DOM and CSS animation.',
                date: 'January, 2016',
                img: '/img/projects/menupro.jpg',
                type: 'Client',
                appType: 'Script',
                appTypeColor: { backgroundColor: '#ae3738' },
                url: '',
            },
        ],
    },
    {
        title: '2015 year',
        data: [
            {
                title: 'Terry Moye CPA',
                description: 'Simple website for accounting services by using plain HTML, CSS and PHP',
                date: 'December, 2015',
                img: '/img/projects/terry-project.png',
                type: 'Client',
                appType: 'Website',
                appTypeColor: { backgroundColor: '#429934' },
                url: '',
            },
            {
                title: 'Ledinis.lt',
                description: 'Website administration',
                date: 'January 2015',
                img: '/img/projects/terry-project.png',
                type: 'Work',
                appType: 'Website',
                appTypeColor: { backgroundColor: '#429934' },
                url: '',
            }
        ],
    },

];

export {
    portfolioProjects,
}